In [3]:
import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df.set_index("name", inplace=True)

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [4]:
df.to_csv("./data/df_sample.csv")

In [7]:
df.to_csv("./data/df_sample2.csv", index=False)

In [8]:
# JSON 파일로 저장

import pandas as pd

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [9]:
df.to_json("./data/df_sample.json")

In [10]:
# Excel 파일로 저장

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [11]:
df.to_excel("./data/df_sample.xlsx")

In [12]:
df.to_excel("./data/df_sample2.xlsx", index=False)